# src/test/resources/application-test.yml

spring:
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
  datasource:
    url: jdbc:mysql://localhost:3306/chatify_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # --- ğŸ”½ ì•„ë˜ ë‚´ìš©ì„ ì¶”ê°€í•´ì£¼ì„¸ìš” ğŸ”½ ---
  mail:
    username: ${GMAIL_USERNAME} # ì‹¤ì œ ê³„ì •ì¼ í•„ìš” ì—†ìŒ
    password: ${GMAIL_APP_PASSWORD}     # ì‹¤ì œ ë¹„ë°€ë²ˆí˜¸ì¼ í•„ìš” ì—†ìŒ

jwt:
  # ì‹¤ì œ í‚¤ê°€ ì•„ë‹Œ, í…ŒìŠ¤íŠ¸ ì „ìš©ì˜ ì•„ë¬´ í‚¤ë‚˜ ì—¬ê¸°ì— ì§ì ‘ ì…ë ¥í•©ë‹ˆë‹¤.
  secret-key: ${JWT_SECRET_KEY}
  verification-token-expiration-ms: 600000